pystan/model.py

Minor change. Old function is an artifact of the earlier asyncio
approach.

Remove unnecessary function in Model

---

pystan/model.py
tests/test_normal.py

Also updates normal test to be more demanding. Should detect a different
sampler.

Use correct default sampler hmc_nuts_diag_e_adapt

---

pystan/model.py
requirements.txt
tests/test_build_program.py

Requires httpstan version greater than 0.3.1.

Report program compilation errors to user.

---

requirements.txt
test-requirements.txt

Updates `requirements.txt` and `test-requirements.txt`. Should help
avoid surprises when a version of a package is released with breaking
changes.

Limit versions of packages used

---

requirements.txt
stan/model.py

improve sampling error message

---

stan/fit.py
tests/test_basic_normal.py
tests/test_eight_schools.py
tests/test_fit_basic_matrix.py
tests/test_fit_basic_scalar.py
tests/test_fit_basic_vector.py
tests/test_matrix_params.py
tests/test_normal.py

Sample parameters such as `lp__` and sampler parameters such as
`stepsize__` are now available to `Fit` instances.

Fit instances have sample and sampler parameters

---

requirements.txt
stan/model.py
tests/test_basic_bernoulli.py

Depends on a minor unreleased fix in httpstan.

tests: add bernoulli tests

---

CONTRIBUTING.rst

doc: add contributing guidelines

---

requirements.txt
tests/test_transformed_data_rng.py

tests: port test_generated_quantities_seed.py

---

stan/model.py

This ensures that data is not changed in-place, which might confuse or even create bugs elsewhere in the code.
See https://github.com/stan-dev/pystan-next/issues/60

Use deepcopy for data in build function

---

requirements.txt

No significant changes in pbr. Should not create any problems.

fix: update pbr version

---

stan/model.py
tests/test_data_validation.py
tests/test_model_build_data.py

Makes one less copy of the values of input `data`. Adds tests.
Related issue #60.

fix: simply code, make one less copy of `data`

---

requirements.txt

fix: pin httpstan to minor version

---

.appveyor.yml

Do not merge until httpstan 0.10.x pin merged.

ci: Add .appveyor.yml for Windows testing

---

tests/test_basic_bernoulli.py
tests/test_corr_matrix.py
tests/test_linear_regression.py

Removes a print statement, uses random seeds to speed up re-running
tests.

test: Clean up three tests

---

stan/model.py
tests/test_user_inits.py

fix: Let users specify initial values

---

CHANGELOG.rst
CHANGES.rst
pyproject.toml
stan/__init__.py

This version is not intended for public release.

feat: Version 3.0.0a12

---

stan/__init__.py

This version needs to match the version in pyproject.toml.

fix: Fix version in __init__.py

---

.readthedocs.yml
docs-requirements.txt
pyproject.toml
tox.ini

Eliminate need to have a separate docs requirements.txt file.

fix: Simplify docs building process

---

README.rst
doc/index.rst
doc/upgrading.rst

Add initial section about upgrading to PyStan 3 from PyStan 2.
Closes #106

docs: Add draft section on upgrading from PyStan 2

---

pyproject.toml
stan/__init__.py

Bump version. The PR also has a commit which removes the need to update __version__ manually.

chore: Bump version to 3.0.0-beta.1

---

doc/getting_started.rst
doc/index.rst
doc/installation.rst
doc/upgrading.rst

Mention need to use `pip install --pre`. Mention that
pandas is not installed by default. Fix code highlighting issue.
Closes #124

docs: Add several clarifications

---

doc/getting_started.rst
doc/index.rst
doc/installation.rst
doc/upgrading.rst

Workaround RST not allowing nested inline markup.
Use directives instead.

docs: Fix restructuredtext formatting [ci skip]

---

stan/model.py

Show user the sampling progress messages Stan sends. These messages
are available from httpstan but are not exposed by PyStan.
Closes #131

feat: Provide user feedback during sampling

---

doc/index.rst
doc/upgrading.rst

Expand notes about upgrading from PyStan 2.

docs: Add warnings, expand upgrading notes

---

.travis.yml

Use Ubuntu Linux 20.04 for testing.

ci: Use ubuntu focal (20.04)

---

pyproject.toml
stan/model.py
tests/test_stanc_warnings.py

Show non-fatal stanc warning messages to user.
Exposes information available since httpstan 2.2.0.
Closes #144

feat: Show non-fatal stanc warnings

---

.github/stale.yml

Stale bot does not seem to be working.  Use a standard config. Perhaps
it will fix the problem.

ci: Update stale bot config

---

stan/model.py

Silence exception messages after a KeyboardInterrupt.
Closes #133

feat: Silence exception after KeyboardInterrupt

---

pyproject.toml

Use Stan 2.25.0. Update httpstan version and bump PyStan version.

feat: Use Stan 2.25.0

---

tests/test_fit_cache.py

tests: Fix flaky test case

---

.github/workflows/main.yml
tests/test_fit_cache.py

Run tests in GitHub Actions, testing against Linux (Ubuntu 20.04) and macOS (10.14).

ci: GitHub Actions

---

doc/contributing.rst

Make PyStan's goals and non-goals clearer.

docs: Make goals and non-goals clearer

---

stan/model.py

Improve informational text messages displayed to user.  Standardize
color scheme. Present information in a more logical sequence.  For
example, the completed progress bar is shown after Stan C++ warning and
informational messages, giving the user the (correct) sense that
sampling completes after these messages were received.
Closes #164

fix: Improve informational text messages

---

pyproject.toml

chore: Bump version [ci skip]

---

stan/fit.py
tests/test_basic_bernoulli.py
tests/test_eight_schools.py
tests/test_eight_schools_large.py
tests/test_fit_basic_scalar.py
tests/test_normal.py

The Fit class now implements collections.abc.Mapping. Users can iterate
over a Fit instance and use several of the normal dictionary methods.
Closes #142

feat: Fit implements collections.abc.Mapping

---

pyproject.toml

Bump pystan version, updating httpstan version at the same time.

chore: bump version, update httpstan version

---

pyproject.toml

Use recommended poetry [build-system] config.

fix: Use recommended poetry [build-system] config

---

pyproject.toml

Use more recent httpstan which includes the Stan 2.26.1 fix.

fix: Use fixed Stan 2.26.1

---

doc/faq.rst
doc/index.rst

Add FAQ answer about Jupyter Notebook.
Closes #217

docs: Add FAQ item on Jupyter Notebook

---

doc/faq.rst

Mention JupyterLab in the FAQ. This is a useful addition
in case people are searching for it.
This commit also uses a second-level heading for questions in the FAQ
section. This will allow linking to specific questions.

docs: Mention JupyterLab and use heading

---

stan/model.py

Improve typing in model.py. In particular, make clear
what our current expectations about the `data` dictionary are.
`data` must be a Python dictionary with values of type
`Union[int, float, Sequence[Union[int, float]], np.ndarray]`.
Nested sequences of Union[int, float] should work. Python's
`typing` library does not currently allow one to describe recursive
types.
Closes #225

fix: Improve typing in model.py

---

doc/faq.rst

docs: Add FAQ item about Windows

---

stan/model.py

Allow arbitrary requests to httpstan's create fit endpoint.
This is needed in order to simplify adding a `fixed_param`
method. Previously the code making the request to the
create fit endpoint was tied into the `sample` method.
Docstrings have been lightly edited. An ``hmc_nuts_diag_e_adapt`` method
has been added, making explicit what was implicit before.
This commit makes no substantive changes to the code.

refactor: Allow arbitrary requests to create fit endpoint

---

pyproject.toml

Update version of depended-upon packages.

chore: Update versions of dependencies

---

pyproject.toml

chore: Bump version.

---

.github/workflows/main.yml

ci: Test using Python 3.9

---

stan/model.py

Include default `data` value (an empty dict) in function signature.
We cannot use a normal empty dict because using a mutable
data type as a default argument value in a function is almost
always a bad idea. Indeed, doing this is perhaps the canonical
gotcha in Python programming. See
<https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments>
for a full description of the problem.
With the arrival of type annotations, however, we really do want to
indicate that the default value is an empty dict.  We indicate default
values everywhere else, so not doing it in this case is confusing.
The solution here is to create a superficial implementation of
`frozendict` (which really should be part of the standard library,
alongside `frozenset`). See the rejected PEP416 for why
it is …

fix: Include default `data` value in function signature

---

.github/ISSUE_TEMPLATE/config.yml

Fix missing key in issue template.

chore: Fix issue template

---

stan/model.py

Improve user interface messages during build and sample.  Report build
progress. Sampling progress reports now resemble those you would see
when doing `git clone` (for a large repository).
These changes make use of poorly-documented features in `clikit`.
Since `clikit` is used by `poetry`, relying on these features seems
safe.
Closes #190

feat: Improve UI messages during build and sample

---

stan/model.py
tests/test_build_exceptions.py
tests/test_build_program.py
tests/test_sample_exceptions.py

Improve display of init failed error, syntax error, and semantic error. Closes two issues (referenced in commits). PR also contains a fix to a recently introduced, UI-related variable reference error.

UI: improve display of init failed error, syntax error, and semantic error

---

stan/model.py

Improve display on non-ANSI terminals.
Closes #287

fix: UI: behave better in non-ANSI terminals

---

.github/workflows/main.yml

ci: Test on fedora latest and ubuntu latest

---

.github/ISSUE_TEMPLATE/bug_report.md

Update issue template. Ask for operating system details.
Closes #302

chore: Update issue template [skip ci]

---

.github/workflows/main.yml
doc/faq.rst
doc/installation.rst

List officially supported linux distributions and indicate those which appear to work fine.

List officially supported linux distributions

---

scripts/tag-release

Align with httpstan's version.

fix: Improve tag release script

---

pyproject.toml
tests/test_stanc_warnings.py

Bump version for Stan 2.29.0.
httpstan now at 4.7.0.

chore: Bump version

---

pyproject.toml

Update mypy version 0.961 from  to 0.982.

chore: Update mypy

---

.github/workflows/main.yml
.github/workflows/publish.yaml

ci: Use actions/setup-python@v4

---

.github/workflows/main.yml

Fixes #375
(I hope this is the right way?)

Added Python 3.11 to github workflows.

---

README.rst
doc/getting_started.rst
doc/index.rst
tests/test_basic_bernoulli.py
tests/test_eight_schools.py
tests/test_eight_schools_large.py
tests/test_fit_basic_array.py
tests/test_fit_basic_vector.py
tests/test_fit_shape.py
tests/test_model_build_data.py
tests/test_numpy_data.py

Use updated array syntax on tests and docs.

test: array syntax

---

.github/workflows/main.yml
.github/workflows/publish.yaml

Fixes several issues involving urllib3.

ci: Use more recent poetry for publishing to PyPI

---

pyproject.toml

Newer version required for Python 3.12

fix: Update pysimdjson required version
