README.rst, doc/source/getting_started.rst, doc/source/library/index.rst, pystan/__init__.py, pystan/model.py, tests/test_corr_matrix.py, tests/test_eight_schools.py, tests/test_matrix_params.py, tests/test_normal.py
Previous name was `compile`. New name is `build`. This name should be
more familiar to people who do not use compilers. RStan also plans
to use the verb `build`.
Closes #9
=> Renames function for compiling programs to `build`

README.rst, pystan/fit.py, pystan/model.py, requirements.txt, tests/test_eight_schools.py, tests/test_fit_basic_array.py, tests/test_fit_basic_matrix.py, tests/test_fit_basic_scalar.py, tests/test_fit_basic_vector.py, tests/test_normal.py
Allows users to get parameters via `__getitem__`. For example,
if a user has a Fit instance `fit` which has a matrix parameter `beta`
which has shape (3, 2) in Stan, `fit["beta"]` returns an array
with shape (3, 2, num_samples * num_chains).
This commit changes the shape of the array which is used to store
draws internally.
=> Add Fit class __getitem__

stan/model.py, tests/test_data_validation.py, tests/test_eight_schools.py
Values which resemble Numpy `ndarray` and pandas `Series` should be
accepted. They will be converted into (JSON-serializable) lists.
Closes #51
=> feat: `Model` accepts a wider range of data

tests/test_basic_bernoulli.py
Old tests contained unreachable check for exception messages.
=> test: fix incorrect use of pytest.raises

stan/fit.py, tests/test_basic_bernoulli.py, tests/test_repr.py
Adds a minimally informative __repr__ for the Fit class. Also adds a
simple __len__ which reports the number of parameters.
Closes #41
Closes #92
=> feat: Add __repr__ and __len__ for Fit

CHANGELOG.rst, doc/source/release-howto.rst
The changelog will be automatically generated from commit messages in
the future. Updating it manually is a conspicuous waste of developer time.
=> docs: Remove changelog

pyproject.toml, stan/common.py, stan/model.py, tests/test_basic_bernoulli.py, tests/test_build_program.py, tests/test_httpstan_health.py, tests/test_httpstan_unused_port.py, tests/test_model_build_data.py
The commit messages have specific details. There are two major changes to align things with httpstan:
- Use async http requests instead of `requests`. This is what httpstan has always done in its tests.
- Remove two tests which are failing due to the shift from "stanc2" to stanc3.
=> Update PyStan to work with httpstan 2.x

doc/contributing.rst
Incorporates material moved from httpstan's contribution guidelines.
=> docs: Update contribution guidelines

.travis.yml
The .travis.yml file now resembles httpstan's version.
=> ci: Align .travis.yml with httpstan's

.readthedocs.yml, .travis.yml, stan/__init__.py
It is easy to forget to update the version string
in the `__init__.py` file. With this change the
version is stored in a single place (`pyproject.toml`).
=> fix: Provide __version__ via importlib

doc/contributing.rst
RST has stricter rules about headers than markdown.
=> docs: Fix headers in contributing guide

pyproject.toml
numpy is obviously a requirement. Everything works without
this requirement because `httpstan` requires numpy. We
cannot assume that this will always be the case.
=> fix: Add missing numpy requirement

pyproject.toml
Fixes #123
This PR fixes the missing `pytest.marker.asyncio` by installing `pytest-asyncio`.  `pytest` installation replaced with `pytest-cov`.
Packages are updated to be aligned with httpstan.
=> test: Align testing packages with httpstan

pyproject.toml, stan/model.py
Compiling the Stan program takes time. Give the user some indication of
what is happening.
Note that we cannot use a progress indicator here because httpstan
redirects everything sent to stderr to /dev/null to avoid overwhelming
the user with a flood of compiler info and warning messages. Progress
indicators can be used elsewhere.
Closes #111
=> feat: Provide user feedback during compilation

pyproject.toml
Use pytest 5.x, not pytest 6.x.
Tests have not been updated for pytest 6.x.
Closes #148
=> fix: Use pytest 5.x

.github/workflows/publish.yaml
Publish wheel to PyPI. Only publish if the commit is tagged.  Uses
Github Actions.
This particular commit only enables uploading to Test PyPI. If
everything works, an additional commit can switch over to the real
thing.
Closes #89
=> ci: Publish wheel to PyPI

stan/model.py, tests/test_logger_messages.py, tox.ini
Show non-fatal info and warning messages to user.
Previously logger messages would only be displayed if
sampling aborted.
Closes #69
=> feat: Show non-fatal logger messages to use

stan/model.py
Show cumulative iterations across all chains.
Previously users were shown the progress of the slowest chain.
Cumulative iterations is a better measure of progress.
=> fix: Show cumulative iterations, not slowest chain

.github/workflows/publish.yaml
For future reference, to upload to testpypi with poetry one
needs to first issue the following poetry command:
poetry config repositories.testpypi https://test.pypi.org/legacy/
=> ci: Enable github actions publish workflow

stan/model.py, tests/test_fit_cache.py
Delete fits which are uncacheable. Draws from a model
made without setting a random seed will never be retrieved a
second time because the random seed is unavailable. Users
who do want their fits to be cached should set a random seed.
This fix helps solve the problem of the cache growing without limit.
The cache will now grow much slower.
Closes #154
=> fix: Delete uncacheable fits

pyproject.toml, stan/fit.py, stan/model.py
Adapt to httpstan's new protobuf message schema.
See commit 91964cb073635cd07d38617fdeb6d3f3815fe3eb in
httpstan.
The protocol buffer message now uses protocol buffers `bytes` types
where previously protocol buffers `string` types were used.
=> feat: Adapt to new protocol buffer message schema

.travis.yml
Test on macOS. Testing on macOS should
allow us to catch C++ ABI issues.
=> ci: Test on macOS

tests/test_eight_schools_large.py
Check that a schools model with many parameters (160) works.  Prompted
by a unusual macOS bug in late 2020 (#163).
=> test: Verify a model with many parameters works

pyproject.toml, stan/fit.py, stan/model.py, tests/test_nan_inf.py
Make changes required by new version of httpstan. httpstan 4.0
uses JSON instead of Protocol Buffers.
=> fix: Make changes required by httpstan 4.0

tests/test_fit_cache.py
Fixes #179 
Change shutil.disk_usage to combination of os.walk and os.stat to calculate the sum of filesizes.
This PR adds a helper function `file_usage` which calculates bytes used by the files. If used path doesn't exists this function returns 0.
```python
def file_usage(path):
"""Calculate the size used by the files in bytes."""
size = 0
for root, _, files in os.walk(path):
for filename in files:
size += os.stat(os.path.join(root, filename)).st_size
return size
```
=> tests: fix flaky cache tests

.github/workflows/main.yml
Set CI job timeout to 20 minutes. Most jobs
finish in about 10 minutes.
Closes #181
=> ci: Set CI job timeout to 20 minutes

stan/model.py, tests/test_constrain_pars.py
Add constrain_pars method to Model instances: this
method transforms a sequence of unconstrained parameters
to their defined support, optinally including transformed
parameters and generated quantities.
=> feat: Add constrain_pars method to Model

pyproject.toml, stan/model.py, tests/test_unconstrain_pars.py
Add unconstrain_pars method to Model instances: this
method transforms a sequence of constrained parameters
from their defined support to unconstrained space.
=> feat: Add unconstrain_pars to Model

stan/model.py, tests/test_log_prob.py
Added log_prob method to Model instances, allowing users to calculate
the log probability of a list of unconstrained parameters.
This feature is accompanied by a test: the log_prob method is validated
by comparing the output against the log probability (lp__) extracted
from a model fit.
Closes #40
=> feat: Add log_prob method to Model

stan/model.py
Mention the PyStan-specific `num_chains` keyword argument. This
is the only PyStan-specific argument. All other keyword arguments
are passed to the stan::services function.
Closes #112
=> docs: Mention PyStan-specific `num_chains` kwarg

.github/workflows/main.yml, scripts/test
Add a scripts/test script to make clearer how we test the
package. Previously the invocation of pytest was
only "documented" in our CI configuration. Now
it is "documented" in the repository proper in the form of a script.
With luck, anyone thinking to run `scripts/check` will
notice `scripts/test`.
=> fix: add a scripts/test script

doc/conf.py
Give sphinx a package version during development.
Previously sphinx would try to retrieve `stan.__version__`.
This is not available when the package is not installed.
(We use `importlib.metadata.version`)
Fixes exception which occurs when running `script/check`
during development.
=> docs: set version correctly in development

stan/model.py
Display messages from Stan C++ consistently. Previously
logger messages sent with "info" level were shown
differently than messages sent with "warning" level.
Closes #192
=> fix: display logger messages consistently

stan/model.py, tests/test_grad_log_prob.py
Added grad_log_prob method to Model instances, allowing users
to calculate the gradient of the log posterior evaluated at
the unconstrained parameters.
This feature is accompanied by a test: the grad_log_prob method is
validated by comparing the output against an analytical calculation
of the gradient.
=> feat: Add grad_log_prob method to Model

stan/fit.py, tests/test_pickle.py
Correctly use the default class instance pickler.  Previously the code
relied on the class's `__init__` method being called when the instance was
unpickled.  Python's default class instance pickler does not call the
`__init__` method. It calls `__new__` and then updates the instance's class
dictionary. Relevant section of the Python docs:
https://docs.python.org/3/library/pickle.html#pickling-class-instances
Closes #201
=> fix: Correctly use default class instance pickler

stan/model.py
Make Model a frozen dataclass. Making `Model` an
immutable dataclass has many benefits. We get
`__eq__` and `__hash__`, for example.
6 fewer lines, too. h/t [PEP557](https://www.python.org/dev/peps/pep-0557/)
=> feat: Make Model a frozen dataclass

pyproject.toml
Replace `pystan-next` with `pystan`
=> docs: Update package and docs links

.github/stale.yml
Issues marked as stale after 90 days now.
=> ci: Make stale bot less active

stan/model.py, tests/test_basic_bernoulli.py, tests/test_normal.py
Sample using 4 independent chains by default. This is the
default in RStan. It's also the default in PyStan 2.
=> fix: Align `num_chains` default with RStan

doc/index.rst, doc/plugins.rst, doc/reference.rst, stan/model.py, stan/plugins.py, tests/test_plugins.py
Other developers can change the behavior of PyStan by writing a plugin.
Plugin developers should create a class which subclasses
`stan.plugins.PluginBase`. This class must be referenced in their
package's entry points section.
This feature is added with a particular use in mind. A developer now has
the ability run HMC diagnostics when sampling has completed and alert
the user if any problems are detected.
Closes #129
=> feat: Add plugin system

stan/model.py
Remove an unnecessary assertion. The type for `data` is well-documented
and checked by the type checker.
=> style: Remove unnecessary assertion

pyproject.toml
Add mjcarter to authors in pyproject.toml.
Closes #212
=> docs: Add mjcarter to authors [ci skip]

README.rst
Simplify PyStan citation. Avoids having to visit Zenodo every release.
=> docs: Simplify citation

stan/model.py, tests/test_basic_bernoulli.py
Allow sampling using fixed param method. Method
calls the relevant httpstan endpoint, just like hmc_nuts_diag_e_adapt.
Closes #231
=> feat: Allow sampling using fixed param method

stan/fit.py, tests/test_fit_shape.py
Return empty array with correct shape for 0-dim arrays.
This PR is related to https://github.com/stan-dev/httpstan/pull/547
=> fix: Correct handling for 0-dim arrays.

pyproject.toml
Pin httpstan to major.minor version for reproducibility.
With this change, a given version of pystan will use a specific version
of Stan.  Previously a single version of pystan can use many different
versions of httpstan. Because the version of Stan is tied to the version
of httpstan, pystan could end up using a wide range of Stan versions.
Such behavior is inimical to reproducible research.
Closes #241
=> feat: Pin httpstan to major.minor version for reproducibility

.github/workflows/main.yml
Use macos 10.15. Addresses Github Actions warning.
=> ci: Use macos 10.15

doc/plugins.rst, stan/model.py, stan/plugins.py, tests/test_plugins.py
The plugin hook should always have been named `on_post_sample`.
Naming it `on_post_fit` was a mistake.
Closes #254
=> fix: Rename plugin hook

stan/model.py
This is to just access not `pop` the list `init`. The latter modifies the original, which is undesirable.
=> Do not modify init

doc/reference.rst, stan/model.py, tests/test_eight_schools.py
Document default for num_chains in function signature. Show an example of providing initial values for parameters.
=> docs: Improve documentation for num_chains and init

stan/model.py
Currently, the output of all the chains were the same.
Steps to reproduce:
```python
schools_code = """
data {
int<lower=0> J;         // number of schools
real y[J];              // estimated treatment effects
real<lower=0.0> sigma[J]; // standard error of effect estimates
}
parameters {
real mu;                // population treatment effect
real<lower=0> tau;      // standard deviation in treatment effects
vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
target += normal_lpdf(eta | 0, 1);       // prior log-density
target += normal_lpdf(y | theta, sigma); // log-likelihood
}
"""
schools_data = {"J": 8,
"y": [28,  8, -3,  7, -1,  1, 18, 12],
"sigma": [15, 10, 16, 11, …
```
=> fix: Use different payloads for different chains

stan/model.py, tests/test_basic_bernoulli.py
Adds missing test for the chain id reuse bug (already fixed). Also refactors code to make what is going on in the _create_fit function much clearer.
=> Add test for chain id bug, improve clarity of `_create_fit` code

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation_improvement.md
Use GitHub issue templates to indicate that GitHub issues
are for bug reports and documentation improvements only.
Everything else should go to the Stan Forums.
=> chore: Add GitHub issue templates

stan/model.py
Update sampling progress less frequently. This solves
a UI issue for non-ansi terminals (e.g., jupyter notebook).
Closes #293
=> fix: update progress less frequently

stan/model.py
Docstring of `grad_log_prob` referenced an argument `adjust_transform` that does not exist. Also fixed a typo "evalauted" -> "evaluated".
Minor point, but figured I'd throw a fix up anyways
=> docs: Fixup Model.grad_log_prob docstring

scripts/tag-release
Add simple release tagging script. Should help
avoid accidental typos.
=> chore: Add release helper script

stan/model.py, tests/test_numpy_data.py
This commit makes it easier to use PyStan with numpy integer types.
Numpy integers will be silently converted to Python ints. There
is no loss of precision, risk of overflow, etc.
Note that this adds support in PyStan only for numpy integer types.
Floats are more complicated because Python floats are not necessarily
compatible with numpy floats (e.g., np.float128).
Closes #326
=> feat: Convert numpy integers in `data` to Python int

scripts/tag-release
Fix minor bash errors in tag-release script.
=> ci: Fix bash errors in tag-release script

README.rst, doc/index.rst, doc/installation.rst, doc/upgrading.rst
Supported versions of Python are now reliably communicated via PyPI.
=> docs: Remove outdated mention of Python 3.7

stan/fit.py, tests/test_basic_bernoulli.py, tests/test_normal.py
Fixes #366 
Fixes the formula to calculate `num_samples_saved`.
Updates a test in `tests/test_normal.py` to hit this specific problem for both `num_samples` and `num_warmup` when `save_warmup=True`.
=> fix: Update `num_samples_saved` formula in `fit.py`

pyproject.toml
httpstan now at 4.9.0 (Stan 2.31.0)
Reminder that in poetry, a tilde version requirement pins the minor version. That is, ~1.2.3 means >=1.2.3,<1.3.0.
=> feat: Use Stan 2.31.0

pyproject.toml
httpstan now at 4.10.0 (Stan 2.32.0).
Pin httpstan to >=4.10,<4.11.
Reminder that in poetry, a tilde version requirement pins the minor version. That is, ~1.2.3 means >=1.2.3,<1.3.0.
=> feat: Use Stan 2.32.0

doc/faq.rst
I have added a section to the FAQs that describe how pystan can be installed when using macOS and a M2 chip. The usual way of installing pystan and all it dependencies did not work for me.
=> docs: Added installation guide for macOS with M2 chips to FAQ.

pyproject.toml, tests/test_eight_schools.py, tests/test_fit_basic_matrix.py, tests/test_fit_shape.py, tests/test_stanc_warnings.py
httpstan now at 4.11.0 (Stan 2.33.0).
Pin httpstan to >=4.11,<4.12.
Reminder that in poetry, a tilde version requirement pins the minor version. That is, ~1.2.3 means >=1.2.3,<1.3.0.
=> feat: Use Stan 2.33.0

.github/workflows/main.yml, docs-requirements.txt, pyproject.toml, stan/fit.py
httpstan now at 4.12.0 (Stan 2.34.1).
=> feat: Use Stan 2.34.1
